[test]
# Configuration simple pour les tests avec Bun
# preload = ["./test/setup.ts"]
coverage = true

# Variables d'environnement pour les tests
# Note: timeout et env ne sont pas supportés dans bunfig.toml
# Utiliser les options CLI ou les variables d'environnement directement
